// frontend/src/components/ResultCard.jsx
/**
 * Displays the AI prediction result with confidence score,
 * risk level, SHAP factor breakdown, and the mandatory disclaimer.
 */
export default function ResultCard({ result, onReset }) {
  const { prediction, confidence_score, risk_level, top_contributing_factors, disclaimer } = result;

  const isPositive = prediction === "positive";

  const riskConfig = {
    high:     { bg: "bg-danger-50",    border: "border-danger-200",    text: "text-danger-700",    badge: "High Risk",    icon: "M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" },
    moderate: { bg: "bg-warning-50",   border: "border-warning-200",   text: "text-warning-700",   badge: "Moderate Risk", icon: "M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" },
    low:      { bg: "bg-success-50",   border: "border-success-200",   text: "text-success-700",   badge: "Low Risk",      icon: "M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" },
  };

  const cfg = riskConfig[risk_level] || riskConfig.low;
  const confidencePct = Math.round(confidence_score * 100);

  return (
    <div className="max-w-3xl mx-auto space-y-6 animate-in fade-in zoom-in-95 duration-500">
      <div className={`rounded-3xl border ${cfg.border} ${cfg.bg} p-8 relative overflow-hidden`}>
        {/* Abstract background pattern */}
        <div className="absolute top-0 right-0 -mt-4 -mr-4 w-32 h-32 bg-white/20 rounded-full blur-3xl" />
        
        <div className="flex items-center justify-between mb-8">
          <div>
            <h1 className="text-2xl font-bold text-slate-900">Analysis Result</h1>
            <p className="text-sm text-slate-500 mt-1">Generated by AI Diagnostic Engine v1.0.0</p>
          </div>
          <div className={`flex items-center gap-2 px-4 py-2 rounded-full border ${cfg.border} bg-white shadow-sm`}>
            <svg className={`w-5 h-5 ${cfg.text}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d={cfg.icon} />
            </svg>
            <span className={`text-sm font-bold uppercase tracking-wider ${cfg.text}`}>
              {cfg.badge}
            </span>
          </div>
        </div>

        <div className="flex flex-col md:flex-row items-center gap-10 py-4">
          <div className="relative w-48 h-48 flex-shrink-0">
            {/* Circular Progress Bar for Confidence */}
            <svg className="w-full h-full transform -rotate-90">
              <circle
                cx="96" cy="96" r="88"
                stroke="currentColor"
                strokeWidth="12"
                fill="transparent"
                className="text-white/50"
              />
              <circle
                cx="96" cy="96" r="88"
                stroke="currentColor"
                strokeWidth="12"
                fill="transparent"
                strokeDasharray={552.92}
                strokeDashoffset={552.92 * (1 - confidence_score)}
                strokeLinecap="round"
                className={`${isPositive ? "text-danger-500" : "text-success-500"} transition-all duration-1000 ease-out`}
              />
            </svg>
            <div className="absolute inset-0 flex flex-col items-center justify-center">
              <span className="text-4xl font-black text-slate-900">{confidencePct}%</span>
              <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Confidence</span>
            </div>
          </div>

          <div className="flex-1 text-center md:text-left space-y-4">
            <div className={`text-5xl font-black tracking-tight ${isPositive ? "text-danger-600" : "text-success-600"}`}>
              {isPositive ? "Positive" : "Negative"}
            </div>
            <p className="text-slate-600 leading-relaxed max-w-md mx-auto md:mx-0">
              Based on the provided symptoms and exposure history, the model has detected {isPositive ? "strong indicators" : "no significant evidence"} of a chikungunya infection.
            </p>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="md:col-span-2 bg-white rounded-3xl border border-slate-200 p-8 shadow-sm">
          <h2 className="text-lg font-bold text-slate-900 mb-2">Diagnostic Insights</h2>
          <p className="text-sm text-slate-500 mb-8">
            The following factors contributed most significantly to this prediction according to SHAP analysis.
          </p>
          
          <div className="space-y-6">
            {top_contributing_factors.map(({ feature, impact }) => {
              const positive = impact > 0;
              const pct = Math.min(Math.abs(impact) * 200, 100);
              const label = feature.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
              return (    
                <div key={feature} className="group">
                  <div className="flex justify-between items-end mb-2">
                    <span className="text-sm font-semibold text-slate-700 group-hover:text-brand-600 transition-colors">{label}</span>
                    <span className={`text-xs font-bold px-2 py-0.5 rounded-md ${positive ? "bg-red-50 text-red-600" : "bg-blue-50 text-blue-600"}`}>
                      {positive ? "+" : ""}{impact.toFixed(3)}
                    </span>
                  </div>
                  <div className="h-2 w-full bg-slate-100 rounded-full overflow-hidden">
                    <div
                      className={`h-full rounded-full transition-all duration-1000 ${positive ? "bg-danger-400" : "bg-blue-400"}`}
                      style={{ width: `${pct}%` }}
                    />
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        <div className="space-y-6">
          <div className="bg-brand-900 text-white rounded-3xl p-8 shadow-xl shadow-brand-100 relative overflow-hidden">
            <div className="absolute top-0 left-0 w-full h-full opacity-10 pointer-events-none">
              <svg width="100%" height="100%" viewBox="0 0 100 100" preserveAspectRatio="none">
                <path d="M0 100 C 20 0 50 0 100 100" stroke="white" fill="transparent" />
              </svg>
            </div>
            <h3 className="text-lg font-bold mb-4 relative">Next Steps</h3>
            <ul className="space-y-4 text-sm text-brand-100 relative">
              <li className="flex items-start gap-3">
                <div className="w-5 h-5 rounded-full bg-brand-700 flex items-center justify-center flex-shrink-0 mt-0.5">1</div>
                Consult with a healthcare professional immediately.
              </li>
              <li className="flex items-start gap-3">
                <div className="w-5 h-5 rounded-full bg-brand-700 flex items-center justify-center flex-shrink-0 mt-0.5">2</div>
                Maintain hydration and rest.
              </li>
              <li className="flex items-start gap-3">
                <div className="w-5 h-5 rounded-full bg-brand-700 flex items-center justify-center flex-shrink-0 mt-0.5">3</div>
                Avoid mosquito contact to prevent spread.
              </li>
            </ul>
          </div>

          <div className="bg-white rounded-3xl border border-slate-200 p-8 shadow-sm">
            <h3 className="text-sm font-bold text-slate-900 mb-4 uppercase tracking-widest">Actions</h3>
            <div className="space-y-3">
              <button
                onClick={onReset}
                className="w-full py-3 bg-brand-600 hover:bg-brand-700 text-white font-bold rounded-xl shadow-lg shadow-brand-100 transition-all"
              >
                New Assessment
              </button>
              <button
                onClick={() => window.print()}
                className="w-full py-3 bg-white border border-slate-200 text-slate-600 hover:bg-slate-50 font-bold rounded-xl transition-all flex items-center justify-center gap-2"
              >
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
                </svg>
                Export Report
              </button>
            </div>
          </div>
        </div>
      </div>

      <div className="p-6 bg-slate-900 rounded-3xl text-slate-400">
        <div className="flex gap-4">
          <div className="text-warning-500 flex-shrink-0">
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
            </svg>
          </div>
          <p className="text-xs leading-relaxed italic">
            <strong>Professional Medical Disclaimer:</strong> {disclaimer}
          </p>
        </div>
      </div>
    </div>
  );
}
